name: ternakami
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: 3.3.1
  camera: 0.11.0+1
  flutter:
    sdk: flutter
  dio: 5.5.0+1
  mime: 1.0.5
  image_picker: 1.1.2
  crop: 0.5.5
  image_gallery_saver: 2.0.3
  permission_handler: 11.3.1
  path_provider: 2.1.3
  another_flutter_splash_screen: 1.2.1
  flutter_launcher_icons: 0.13.1
  logging: 1.2.0
  http_parser: ^4.0.2
  curved_navigation_bar: ^1.0.6
  introduction_screen: ^3.1.14
  intl: ^0.17.0
  google_fonts: ^6.2.1
  easy_image_viewer: ^1.5.1
  smooth_page_indicator: ^1.2.0+3
  loading_animation_widget: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\gambar\login_image.png
    - assets\gambar\regis.png
    - assets\gambar\onboarding2.png
    - assets\gambar\onboarding1.png
    - assets\gambar\onboarding3.png
    - assets\gambar\logo.png
    - assets\animations\sukses.gif